### ISSUE TITLE
Office 365/Outlook Repeatedly asking for password

### ISSUE THREAD

**Issue by brown921** [MicrosoftDocs/OfficeDocs-Support#43]
Working on Mac OS 10.15 on iMac and same OS 10.15 on MacBook Air. On iMac I am getting the repeated and annoying prompts for my password for work email via Office 365 through Outlook desktop app. I've tried all of the steps listed above - no joy; its still happening. Oddly, I am getting no prompts or requests for password on the MacBook Air. What is the next level of troubleshooting? Thanks!

-Justin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18c63a16-9c5d-cfb6-f7d8-8dde68a8cfbc
* Version Independent ID: 30be97ca-1cbd-83ec-1ac0-ba654dd21ba5
* Content: [Outlook 2016 for Mac repeatedly prompts for authentication - Outlook](https://docs.microsoft.com/en-us/outlook/troubleshoot/sign-in/repeatedly-prompts-authentication#feedback)
* Content Source: [Outlook/Mac/sign-in/repeatedly-prompts-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Mac/sign-in/repeatedly-prompts-authentication.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by Cloud-Writer** [comment]
@brown921, the issue seems to have been resolved. Would you please confirm? Thanks!

**Comment by davidbernard04** [comment]
Personally I was still getting the issue yesterday, until I disabled the auto-discover using this Apple Script:

    tell application "Microsoft Outlook"
        set background autodiscover of exchange account 1 to false
    end tell

No more prompt for password since.

(MacOS 10.14.5 and Outlook 16.27)

**Comment by v-ami** [comment]
Hello, 

I tried the steps suggested by @davidbernard04 and it showed an error.

Any insight on the issue will be much appreciated. Help!

**Comment by v-ami** [comment]
@Cloud-Writer if I may request you to please if this has been resolved yet, if it has been what exactly is the fix?

**Comment by Cloud-Writer** [comment]
@v-ami, I will follow up with a SME to figure out the latest status and let you know.

**Comment by v-ami** [comment]
@Cloud-Writer Thank you so much, I will wait for an update.

**Comment by Cloud-Writer** [comment]
@v-ami , this issue is being investigated. Would you please log a support case via [in-app](https://support.office.com/en-us/article/Contact-support-within-Outlook-for-Mac-d0410177-8e65-4487-93f7-206a3a3d71a8) support and provide the relevant details? Thanks!

**Comment by zchoate** [comment]
This appears to be a repeated issue with a Mac I am working with. We've gone in multiple times with the workaround to see the same issue come up shortly after. We'll give the autodiscover option a try but that doesn't seem like a permanent fix. Is there an appropriate avenue to troubleshoot the issue?

**Comment by Cloud-Writer** [comment]
@zchoate, this issue is being investigated. Would you please file a support case via in-app support? Thanks!

**Comment by raulipadding** [comment]
Could this relate to moments of switching network connection type from Wi-Fi to mobile 4G ? Case: Outlook is on while in Wi-Fi. Swap to 4G. And a bit later or even next day back in Wi-Fi and issue is up. Just trying to remember how this keeps repeating.

**Comment by sveland** [comment]
This is happening to me also. I had just resolved an issue where blank authentification boxes appeared. I cannot access the in-app support to file a support case (nothing happens when I click on that function in Outlook), so I'm hoping this issue is being resolved.

**Comment by Cloud-Writer** [comment]
Microsoft Support is still investigating this issue. For those of you unable to file a Support case, you probably need to reset your Apple keychain. Here are the steps to do that if you need them:

1. Close Outlook and other Office apps you have open (like Word, PowerPoint, or Excel).
2. Press Command + Space (or press the Spotlight icon on the menu bar), and search for "Keychain Access" in Spotlight, and select it from the list of results.
3. After the Keychain Access opens, select File on the menu bar, and then select Lock All Keychains. Enter your password if you're prompted to do so.
4. Then select File again, and select Unlock Keychain “login.”

After you do this, your Apple Keychain will allow credentials to be stored, and you should be able to contact Support.

**Comment by earthsound** [comment]
I wanted to add some notes about our workaround for this because sometimes just deleting those entries in keychain isn't (always) enough. Our users having trouble are using O365 accounts in combination with Duo (but Duo doesn't seem to be the problem). This is an issue that has been around for several years going back to at least Outlook 2016 for Mac. It doesn't crop up every day/week/month, isn't related to password or other issues specific to an account, and appears to be a problem with Outlook/Keychain interaction. 

- We quit all Office related apps.
- Open Keychain Access > (View > show invisible items) > search for and remove entries related to "exchange", "office", "adal"
- Restart the computer 
- Lock the login entry within Keychain
- Open Outlook > input password to unlock login in Keychain
- In Outlook > login to any accounts that you're prompted for
- In Outlook > Tools > Accounts > input the password into the email account(s) you're having trouble with
- Restart Outlook

Using all of the above has resolved this for us when the usual workaround (just deleting the entries in Keychain) doesn't work. YMMV
